### ISSUE TITLE
In void reverse() usage of new node swap

### ISSUE THREAD

**Issue by vahini01** [grapheo12/algoLab#3]
"Reverse your doubly linked list. Once the doubly linked list is created, you SHOULD NOT create
any new node and change data field of any node."
       we are not supposed to create any new node according to question.Creating node swap might contradict the question.

**Comment by r7919** [comment]
- No new node is created in the reverse function 
- A **structure node pointer** is created for swapping head and tail 
- struct node *temp;
- However, they can be swapped without using a temp pointer

**Comment by grapheo12** [comment]
Since we are storing XOR (commutative) there is no way of distinguishing between left and right pointers. So how do I reverse it without swapping the head and the tail?

**Comment by r7919** [comment]
yes this is the only way which makes sense
Since this list is symmetric
There's nothing to do with reversing

**Comment by vahini01** [comment]
- There might be a problem if we swap without using swap(temp) pointer
`      *head=(struct` node*)((unsigned long int)*head+(unsigned long int)*tail);
	*tail=(struct node*)((unsigned long int)*head-(unsigned long int)*tail);
	*head=(struct node*)(((unsigned long int)*head-(unsigned long int)*tail)/2);`
- We cannot add pointers directly as generally pointer addition is different from normal addition 
- And this code is giving Segmentation fault (core dumped)

**Comment by r7919** [comment]
// these lines work
//removed temp pointer 
//swapping two pointers without using the third pointer
`void reverse(struct node **head, struct node **tail) // since it is symmetric`
`{`
   `(*head) = (struct node*)((uintptr_t)(*head) +(uintptr_t)(*tail));`
    `(*tail) = (struct node*)((uintptr_t)(*head) - (uintptr_t)(*tail));`
     ` (*head) = (struct node*)((uintptr_t)(*head) - (uintptr_t)(*tail));`
`}`

**Comment by grapheo12** [comment]
Is `assignment1.c` giving Segfault? It ran perfectly on my machine.
